Repository submariner-io/enhancements, pull requests merged in 2022-08, with the labels that each got.

#129 Run dependent issues check only on open/edit
  .github/workflows/dependent-issues.yml
Labels: bug

#128 Submariner metrics redesign
  submariner-operator/submariner-metrics-redesign.md
Labels: enhancement

#103 cable-driver: Overlay over IPSec transport mode support
  submariner/IPSec-transport-mode.md
  submariner/images/vxlan-over-ipsec-transport.png
Labels: enhancement, blocked-on-rereview
